#!/usr/bin/env python3
# Originally extracted from a Lean 4 verification project and genericized for the proof-skills toolkit.
"""
templates_to_md.py — convert templates/Template_*.lean to Markdown.

Converts each `/-! ... -/` block to a Markdown section and wraps every
intervening Lean source span in a ```lean ... ``` fence.

Usage:
    python3 scripts/templates_to_md.py            # convert all templates
    python3 scripts/templates_to_md.py --check    # just print what would change
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DOCSTRING_RE = re.compile(r"/-!(.*?)-/", re.DOTALL)


def split_blocks(text: str) -> list[tuple[str, str]]:
    """Return list of ('doc'|'code', content) tuples in source order."""
    blocks: list[tuple[str, str]] = []
    pos = 0
    for m in DOCSTRING_RE.finditer(text):
        if m.start() > pos:
            code = text[pos : m.start()].strip("\n")
            if code.strip():
                blocks.append(("code", code))
        doc = m.group(1).strip("\n")
        if doc.strip():
            blocks.append(("doc", doc))
        pos = m.end()
    if pos < len(text):
        tail = text[pos:].strip("\n")
        if tail.strip():
            blocks.append(("code", tail))
    return blocks


def render_md(blocks: list[tuple[str, str]], stem: str) -> str:
    out: list[str] = []
    out.append(f"<!-- generated by scripts/templates_to_md.py from {stem}.lean -->")
    out.append(
        "<!-- DO NOT edit this file directly; edit the .lean source under "
        "templates/ then re-run the script. -->"
    )
    out.append("")
    for kind, body in blocks:
        if kind == "doc":
            out.append(body.rstrip())
        else:
            out.append("```lean")
            out.append(body.rstrip())
            out.append("```")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def convert_file(src: Path, dst_dir: Path, check: bool) -> bool:
    text = src.read_text(encoding="utf-8")
    blocks = split_blocks(text)
    md = render_md(blocks, src.stem)
    dst = dst_dir / (src.stem + ".md")
    if check:
        existing = dst.read_text(encoding="utf-8") if dst.exists() else ""
        if existing != md:
            print(f"WOULD UPDATE {dst}")
            return True
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(md, encoding="utf-8")
    print(f"wrote {dst} ({len(md)} bytes from {len(text)} src bytes)")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--src-dir",
        type=Path,
        default=Path("templates"),
        help="Directory containing Template_*.lean files",
    )
    ap.add_argument(
        "--dst-dir",
        type=Path,
        default=Path("templates"),
        help="Directory to write .md files (default same as src)",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="Do not write; report whether output would change",
    )
    args = ap.parse_args()

    src_dir: Path = args.src_dir
    if not src_dir.exists():
        print(f"ERROR: source dir not found: {src_dir}", file=sys.stderr)
        return 2
    files = sorted(src_dir.glob("Template_*.lean"))
    if not files:
        print(f"no Template_*.lean files under {src_dir}", file=sys.stderr)
        return 1

    drift = False
    for f in files:
        drift |= convert_file(f, args.dst_dir, args.check)

    if args.check:
        return 1 if drift else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
